"""Reading gate: is a contribution's ``reading`` a possible kana rendering of its
own written ``expression``?

Readings drive Yomitan lookup, so a reading that cannot be produced from the
written form makes the entry unfindable by its real kana and pollutes the
per-source disclosure. UGD-11c-B confirmed nine such cases (all now corrected via
``data/corrections/readings.json``); this module is the fail-closed gate that
keeps a new one from shipping.

Scope and honesty
-----------------
The gate is a **structural** check. For every maximal kanji run in the
expression it asks: can the run be segmented so each kanji takes a reading
attested for it in KANJIDIC2 (plus rendaku/gemination/long-vowel/okurigana
allowances), a small explicit supplementary-reading table, or a whole-run
jukujikun/gikun/ateji allowance? It walks kanji runs as an ordered subsequence
of the reading and tolerates free kana between and after them, because grammar
points are patterns whose particle/inflection tails legitimately diverge from
the reading (``ても始まる`` / ``てもはじまらない``).

What it therefore CANNOT catch is a reading that is structurally valid for the
kanji but wrong for *this sense/context* — e.g. ``下`` read ``した`` when the
grammar point needs ``もと``, or ``如何`` read ``いかが`` when the pattern needs
``いかん``. Both readings are attested for the kanji, so no per-kanji tool can
distinguish them; only semantic review (UGD-11c) can. Six of the nine confirmed
defects were exactly this class. The gate is deliberately not advertised as an
oracle for them; it is the last-line structural guard, complementary to the
semantic pass.

The allowances are derived from the real corpus (see ``scripts/audit_readings.py``)
and are tuned to zero false positives on the shipped dataset while failing closed
on a structurally impossible rendering such as ``結構`` -> ``けっか`` (構 has no
カ reading).
"""

from __future__ import annotations

import functools
import json
import pathlib
import re
import unicodedata

#: Distilled KANJIDIC2 per-kanji reading map (hiragana). Provenance (source
#: sha256, database version, licence) lives in the asset's ``_provenance`` block;
#: it is regenerated by ``scripts/distil_kanjidic.py`` from the pinned upstream.
_DATA_PATH = pathlib.Path(__file__).resolve().parent / "data" / "kanji_readings.json"

_KANJI = re.compile(r"[\u3400-\u4dbf\u4e00-\u9fff\uf900-\ufaff\U00020000-\U0002ffff]")
_KANJI_RUN = re.compile(r"[\u3400-\u4dbf\u4e00-\u9fff\uf900-\ufaff\U00020000-\U0002ffff々]+")

# 連濁 (sequential voicing) and handakuten: a reading may acquire a voiced or
# p-row initial when it is the non-initial element of a compound.
_VOICE = {
    "か": "が", "き": "ぎ", "く": "ぐ", "け": "げ", "こ": "ご",
    "さ": "ざ", "し": "じ", "す": "ず", "せ": "ぜ", "そ": "ぞ",
    "た": "だ", "ち": "ぢ", "つ": "づ", "て": "で", "と": "ど",
    "は": "ば", "ひ": "び", "ふ": "ぶ", "へ": "べ", "ほ": "ぼ",
}
_HANDAKU = {"は": "ぱ", "ひ": "ぴ", "ふ": "ぷ", "へ": "ぺ", "ほ": "ぽ"}
_DEVOICE = {v: k for k, v in _VOICE.items()}

#: Per-kanji readings that are standard/colloquial Japanese but not carried by
#: KANJIDIC2. Kept explicit and tiny; each is a documented, attested reading.
#:  * 言 = ゆう — the colloquial pronunciation of 言う (と言うと=とゆうと).
#:  * 如 = しく/しか — the classical kun of 如く（しく）"to be equal to"
#:    (百聞は一見に如かず＝ひゃくぶんはいっけんにしかず), which KANJIDIC2 lists
#:    only as ごと/ごとし. し is its stem before written okurigana (に如くはない).
#:  * 蔑 = ないがし — the stem of 蔑ろ（ないがしろ）; KANJIDIC2 has only the
#:    undotted whole word, so the written okurigana ろ could not be matched.
SUPPLEMENTARY_READINGS: dict[str, set[str]] = {
    "言": {"ゆう"},
    "如": {"しく", "しか", "し"},
    "蔑": {"ないがし"},
}

#: Whole kanji-RUN readings that are jukujikun / gikun / ateji and cannot be
#: derived per-kanji. Each maps the exact kanji run to every kana reading it
#: legitimately takes. Kept explicit so the gate never guesses a whole-word
#: reading; a run not listed here must be coverable per-kanji.
JUKUJIKUN_RUNS: dict[str, set[str]] = {
    "如何": {"いか", "いかん", "いかが"},  # ateji: いかん/いかが/いか
    "心地": {"ここち"},                    # 心地 = ここち
    "挙句": {"あげく"},                    # 挙句(挙げ句) = あげく
    "甲斐": {"かい", "がい"},              # 甲斐 = かい, rendaku がい (〜がい)
    "下手": {"へた"},                     # 下手 = へた, whole-word reading
}


def _kata_to_hira(text: str) -> str:
    """Fold full-width katakana onto hiragana without an external dependency."""
    out: list[str] = []
    for ch in text:
        code = ord(ch)
        # Katakana block U+30A1–U+30F6 maps onto hiragana at a -0x60 offset;
        # the prolonged-sound mark ー and everything else pass through.
        if 0x30A1 <= code <= 0x30F6:
            out.append(chr(code - 0x60))
        else:
            out.append(ch)
    return "".join(out)


def normalize_kana(text: str | None) -> str:
    """NFKC + katakana→hiragana, the form the gate compares in."""
    return _kata_to_hira(unicodedata.normalize("NFKC", text or ""))


@functools.lru_cache(maxsize=1)
def _kanji_readings() -> dict[str, list[str]]:
    payload = json.loads(_DATA_PATH.read_text(encoding="utf-8"))
    readings = payload.get("readings")
    if not isinstance(readings, dict):
        raise ValueError(f"malformed kanji reading asset: {_DATA_PATH}")
    return readings


@functools.lru_cache(maxsize=200_000)
def _variants(reading: str) -> frozenset[str]:
    """Kana variants a kanji reading may legitimately take inside a compound."""
    out = {reading}
    head, tail = reading[:1], reading[1:]
    if head in _VOICE:
        out.add(_VOICE[head] + tail)
    if head in _HANDAKU:
        out.add(_HANDAKU[head] + tail)
    if head in _DEVOICE:
        out.add(_DEVOICE[head] + tail)
    # 促音化 of the final mora (一回 いち+かい -> いっかい)
    for v in list(out):
        if v[-1:] in ("つ", "く", "ち", "き", "ふ"):
            out.add(v[:-1] + "っ")
    # long-vowel spelling and final -う elision
    for v in list(out):
        out.add(v.replace("ー", "う"))
        out.add(v.replace("おお", "おう"))
        out.add(v.replace("おう", "おお"))
        if v.endswith("う") and len(v) > 1:
            out.add(v[:-1])
    return frozenset(v for v in out if v)


def _readings_for(ch: str) -> set[str]:
    return set(_kanji_readings().get(ch, ())) | SUPPLEMENTARY_READINGS.get(ch, set())


@functools.lru_cache(maxsize=200_000)
def _run_cover(run: str, reading: str, start: int) -> int | None:
    """Position in ``reading`` after covering ``run`` from some index >= ``start``.

    Returns the reading index consumed once the whole kanji ``run`` is covered,
    or ``None`` if it cannot be. Free kana before the run (between the previous
    run and this one) is skipped by trying every start offset.
    """

    def walk(bi: int, ri: int) -> int | None:
        if bi == len(run):
            return ri
        # Whole-run jukujikun/gikun/ateji, anchored at the current position.
        for whole, run_readings in JUKUJIKUN_RUNS.items():
            if run.startswith(whole, bi):
                for rr in run_readings:
                    if reading.startswith(rr, ri):
                        result = walk(bi + len(whole), ri + len(rr))
                        if result is not None:
                            return result
        ch = run[bi]
        if ch == "々" and bi > 0:  # repetition mark takes the previous kanji
            ch = run[bi - 1]
        pool: set[str] = set()
        for r in _readings_for(ch):
            pool |= _variants(r)
        for cand in sorted(pool, key=len, reverse=True):
            if reading.startswith(cand, ri):
                result = walk(bi + 1, ri + len(cand))
                if result is not None:
                    return result
        return None

    for offset in range(start, len(reading) + 1):
        result = walk(0, offset)
        if result is not None:
            return result
    return None


#: A producer's parenthetical ANNOTATION, not furigana. NINJAL writes a sense tag
#: in parentheses on either side of the pair: expression `可能の形 （～れる・～られる）`
#: with reading `～れる（かのう）`. The two sides annotate different things, so no
#: kana-coverage rule can relate them; the pattern outside the parentheses is what
#: the reading actually renders.
_ANNOTATION = re.compile(r"[（(][^）)]*[）)]")

#: A producer's ALTERNATIVE-SPELLING separator. NINJAL, bunpou, bunpro and IMABI
#: list alternative spellings of ONE pattern in a single headword field
#: (`～に即して・～に則して` reading `～にそくして`), so the reading is the reading of each
#: alternative rather than of the concatenation. 43 kanji-bearing rows use it.
_ALTERNATIVE = "・"


def _annotation_stripped(text: str) -> str:
    return _ANNOTATION.sub("", text or "").strip()


def _alternatives(text: str) -> list[str]:
    return [part.strip() for part in (text or "").split(_ALTERNATIVE) if part.strip()]


def is_plausible_reading(expression: str, reading: str | None) -> bool:
    """True when ``reading`` is a structurally possible kana rendering of ``expression``.

    * A missing/empty reading is plausible (nothing to check).
    * ``reading == expression`` is plausible: the merge treats an identical
      reading as a redundant furigana pair and never carries it as furigana, so
      it can never make the entry unfindable.
    * An expression with no kanji is plausible: there is no kanji reading to
      contradict.
    * Parenthetical annotation is removed from both sides first, and each
      alternative spelling is judged separately -- see ``_ANNOTATION`` and
      ``_ALTERNATIVE``. Every alternative must be renderable by at least one of
      the reading's alternatives.
    * Otherwise every maximal kanji run must be coverable, in order, within the
      reading (see the module docstring for the exact rule).

    The notation handling was scoped by measurement over the 1,513 kanji-bearing
    rows that carry a reading: it turns 0 passing rows into failures, turns
    exactly 4 into passes (all NINJAL `A・B` alternative spellings whose reading is
    correct for each alternative), and still rejects the structural defect
    ``結構`` -> ``けっか``.
    """
    if not reading:
        return True
    if normalize_kana(expression) == normalize_kana(reading):
        return True
    expressions = _alternatives(_annotation_stripped(expression))
    readings = _alternatives(_annotation_stripped(reading))
    if not expressions or not readings:
        # Nothing left to compare once annotation is removed.
        return True
    return all(
        any(_covers(candidate, rendering) for rendering in readings)
        for candidate in expressions
    )


def _covers(expression: str, reading: str) -> bool:
    """The kanji-run coverage rule, for one expression against one reading."""
    base = normalize_kana(expression)
    read = normalize_kana(reading)
    if base == read:
        return True
    runs = _KANJI_RUN.findall(base)
    if not runs:
        return True
    position = 0
    for run in runs:
        end = _run_cover(run, read, position)
        if end is None:
            return False
        position = end
    return True


def is_exact_reading(expression: str, reading: str) -> bool:
    """Check a literal spelling before promoting a source reading to a headword.

    Unlike the pattern-reading gate, every kana character and the entire reading
    must match. This rejects missing okurigana, concatenated alternatives and
    readings for a different inflection. It still cannot choose between two
    valid readings of a word; the candidate must come from the source itself.
    """
    base, read = normalize_kana(expression), normalize_kana(reading)
    if not base or not re.fullmatch(r"[ぁ-ゖー]+", read):
        return False

    @functools.lru_cache(maxsize=None)
    def walk(bi: int, ri: int) -> bool:
        if bi == len(base):
            return ri == len(read)
        ch = base[bi]
        if not _KANJI.fullmatch(ch) and ch != "々":
            return read.startswith(ch, ri) and walk(bi + 1, ri + 1)
        for whole, candidates in JUKUJIKUN_RUNS.items():
            if base.startswith(whole, bi):
                for candidate in candidates:
                    if read.startswith(candidate, ri) and walk(bi + len(whole), ri + len(candidate)):
                        return True
        if ch == "々" and bi:
            ch = base[bi - 1]
        for raw in _readings_for(ch):
            for candidate in _variants(raw):
                if read.startswith(candidate, ri) and walk(bi + 1, ri + len(candidate)):
                    return True
        return False

    return walk(0, 0)


def has_kanji(text: str) -> bool:
    return bool(_KANJI.search(text or ""))


__all__ = [
    "SUPPLEMENTARY_READINGS",
    "JUKUJIKUN_RUNS",
    "normalize_kana",
    "is_plausible_reading",
    "is_exact_reading",
    "has_kanji",
]
